name = "descent"
defaultTargets = ["Descent"]
testDriver = "descent_test_driver"
lintDriver = "descent_lint_driver"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "0ee01d5178b24f7a7d1bd7a50beccb773373d01b"

[[lean_lib]]
name = "Descent"
leanOptions = {pp.unicode.fun = true, autoImplicit = false, maxSynthPendingDepth = 3}

[[lean_exe]]
name = "descent_test_driver"
root = "DescentTestDriver"

[[lean_exe]]
name = "descent_lint_driver"
root = "DescentLintDriver"
