name = "descent"
defaultTargets = ["Descent"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.27.0-rc1"

[[lean_lib]]
name = "Descent"
leanOptions = {pp.unicode.fun = true, autoImplicit = false, maxSynthPendingDepth = 3}
